import fs from 'node:fs';
import path from 'node:path';
import { NITS_REGISTRY_VERSION } from './constants.js';
import { isValidModuleId } from './nits-id.js';
import { ensureShadowFile, readShadowFile } from './shadow-file.js';

import type { NitsRegistry } from '../types/nits.js';
import type { ShadowFileRecord } from './shadow-file.types.js';
import type { ReconciliationResult } from '../types/nits.js';

/**
 * Returns the project name inferred from package.json in the current working directory.
 */
export function inferProjectName(cwd: string): string {
  try {
    const pkgPath = path.join(cwd, 'package.json');
    if (fs.existsSync(pkgPath)) {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
      return pkg.name || 'unknown';
    }
  } catch {
    // Failsafe
  }
  return 'unknown';
}

/**
 * Initializes an empty NITS registry state.
 */
export function initNitsRegistry(projectName: string): NitsRegistry {
  return {
    _note: 'This file is generated by Nodulus NITS. Include it in Git.',
    project: projectName || 'unknown',
    version: NITS_REGISTRY_VERSION,
    lastCheck: new Date().toISOString(),
    modules: {}
  };
}

/**
 * Loads the NITS registry from the standardized path (.nodulus/registry.json).
 * Returns null if the file is missing or corrupted.
 */
export async function loadNitsRegistry(cwd: string): Promise<NitsRegistry | null> {
  const fullPath = path.join(cwd, '.nodulus', 'registry.json');
  
  if (!fs.existsSync(fullPath)) {
    return null;
  }

  try {
    const content = await fs.promises.readFile(fullPath, 'utf-8');
    const data = JSON.parse(content);
    
    // Schema Validation
    if (!isValidRegistry(data)) {
      console.warn(`[System] Warning: NITS registry at "${fullPath}" has an invalid structure. Ignoring.`);
      return null;
    }

    if (data.version !== NITS_REGISTRY_VERSION) {
      console.warn(`[System] Warning: NITS registry version mismatch (found ${data.version}, expected ${NITS_REGISTRY_VERSION}).`);
    }

    // Deep validation of module IDs
    for (const id of Object.keys(data.modules)) {
      if (!isValidModuleId(id)) {
        console.warn(`[System] Warning: Corrupt NITS ID found in registry: ${id}. Registry considered invalid.`);
        return null;
      }
    }
    
    return data as NitsRegistry;
  } catch (err: any) {
    console.warn(`[System] Warning: Failed to load NITS registry at "${fullPath}": ${err.message}`);
    return null;
  }
}

/**
 * Valid NitsStatus values — kept in sync with the NitsStatus union type.
 * A record whose status is not in this set is considered corrupted.
 */
const VALID_NITS_STATUSES = new Set<string>([
  'active', 'stale', 'moved', 'candidate', 'deleted'
]);

/**
 * Validates the basic structure of a NITS registry object.
 * Also checks each module record for required fields (CODE-2) and type correctness.
 */
function isValidRegistry(data: any): data is NitsRegistry {
  if (
    !data ||
    typeof data !== 'object' ||
    typeof data.project !== 'string' ||
    typeof data.version !== 'string' ||
    typeof data.lastCheck !== 'string' ||
    !data.modules ||
    typeof data.modules !== 'object'
  ) {
    return false;
  }

  // Validate required fields on every NitsModuleRecord.
  // A partial record (e.g. missing hash or createdAt) would reach reconcile()
  // with undefined values, causing activeHashes to store "undefined" as a key
  // and createRecord to propagate undefined into createdAt (see BUG-3).
  for (const [id, mod] of Object.entries(data.modules)) {
    const m = mod as any;
    const missing = ['name', 'path', 'hash', 'status', 'createdAt', 'lastSeen', 'identifiers']
      .filter(f => m[f] === undefined || m[f] === null);

    if (missing.length > 0) {
      console.warn(
        `[System] Warning: Module record "${id}" is missing required fields: ${missing.join(', ')}. Registry considered invalid.`
      );
      return false;
    }

    // Validate status is a known enum value (guards against corrupted/future registries).
    if (!VALID_NITS_STATUSES.has(m.status)) {
      console.warn(
        `[System] Warning: Module record "${id}" has an unrecognised status "${m.status}". Expected one of: ${[...VALID_NITS_STATUSES].join(', ')}. Registry considered invalid.`
      );
      return false;
    }

    // Validate identifiers is an actual array (not just non-null).
    if (!Array.isArray(m.identifiers)) {
      console.warn(
        `[System] Warning: Module record "${id}" has invalid identifiers field (expected Array, got ${typeof m.identifiers}). Registry considered invalid.`
      );
      return false;
    }
  }

  return true;
}


/**
 * Saves the NITS registry to the standardized path (.nodulus/registry.json).
 * Uses an atomic write strategy (write to .tmp then rename) to prevent corruption.
 */
export async function saveNitsRegistry(registry: NitsRegistry, cwd: string): Promise<void> {
  const fullPath = path.join(cwd, '.nodulus', 'registry.json');
  const tempPath = `${fullPath}.tmp`;
  const dir = path.dirname(fullPath);
  
  if (!fs.existsSync(dir)) {
    await fs.promises.mkdir(dir, { recursive: true });
  }

  // Ensure .gitkeep exists so the directory is always versioned
  const gitkeepPath = path.join(dir, '.gitkeep');
  if (!fs.existsSync(gitkeepPath)) {
    await fs.promises.writeFile(gitkeepPath, '', 'utf-8');
  }

  // Fix [N-49]: Clone to avoid mutating the original object passed by the caller
  const registryToSave: NitsRegistry = {
    ...registry,
    _note: 'This file is generated by Nodulus NITS. Include it in Git.',
    project: inferProjectName(cwd),
    lastCheck: new Date().toISOString()
  };

  // Atomic write: 
  // 1. Write to temporary file
  await fs.promises.writeFile(
    tempPath, 
    JSON.stringify(registryToSave, null, 2), 
    'utf-8'
  );

  // 2. Atomic rename (replaces existing if any)
  await fs.promises.rename(tempPath, fullPath);
}

/**
 * Shadow file scanner — idempotent, never throws.
 *
 * For each discovered module directory:
 *  - If a valid `.nodulus` file already exists → reads and returns it (no-op).
 *  - If missing or corrupted → creates a new one with a fresh `mod_{hex}` ID.
 *
 * Called during Step 2.5 of the bootstrap pipeline, BEFORE NITS reconciliation,
 * so every module enters the reconciler with a stable shadow identity.
 *
 * **Edge case — write permission denied:** `ensureShadowFile` swallows the error
 * and returns the in-memory record regardless. The scanner stores `undefined` for
 * that module so the reconciler falls through to Jaccard. Bootstrap continues.
 *
 * **Edge case — FS race condition (Chokidar `unlinkDir` during scan):** If the
 * directory disappears between discovery and this call (e.g. the user deletes it
 * while the scanner runs), `ensureShadowFile` can throw an `ENOENT`. The
 * try/catch below catches it and excludes the module, treating it as if
 * `shadowFile` were `undefined`. The reconciler will route it to `stale`.
 *
 * @param moduleDirs - Array of {name, dirPath} for each discovered module.
 * @returns Map of `dirPath → ShadowFileRecord` for modules with a valid identity.
 */
export function scanShadowFiles(
  moduleDirs: { name: string; dirPath: string }[]
): Map<string, ShadowFileRecord> {
  const result = new Map<string, ShadowFileRecord>();

  for (const { dirPath } of moduleDirs) {
    try {
      const record = readShadowFile(dirPath);
      if (record) {
        result.set(dirPath, record);
      }
    } catch (err: unknown) {
      // ENOENT or any unexpected error: directory vanished during scan
      // (FS race condition). Exclude this module — it will surface as `stale`
      // in the reconciler and eventually as `deleted` if its shadow ID is gone.
      const msg = err instanceof Error ? err.message : String(err);
      console.warn(
        `[NITS] Shadow file scan skipped for "${dirPath}": ${msg}. Module will be treated as legacy this cycle.`
      );
    }
  }

  return result;
}

/**
 * POST-RECONCILE shadow file writer.
 *
 * Called AFTER reconcile() completes. Creates `.nodulus` shadow files for
 * modules that were resolved via path or Jaccard (Steps 1–3) and do not yet
 * have a shadow file. This ensures they carry a stable ID on every subsequent
 * boot without disrupting the migration path for existing projects.
 *
 * @param result       - The reconciliation result from this boot cycle.
 * @param resolvedDirs - Map of `dirPath → moduleName` for all discovered modules.
 */
export function postReconcileEnsureShadowFiles(
  result: ReconciliationResult,
  resolvedDirs: Map<string, string>,
  modulesRoots: string[]
): void {
  // Only act on modules resolved by path or Jaccard — shadow-file resolved
  // modules already have their file; new modules will get one on the next step.
  const needsShadowFile = [
    ...result.confirmed.filter(r => r.resolvedBy !== 'shadow-file'),
    ...result.moved.map(m => m.record).filter(r => r.resolvedBy !== 'shadow-file'),
    ...result.candidates.map(m => m.record).filter(r => r.resolvedBy !== 'shadow-file'),
    ...result.newModules.filter(r => r.resolvedBy !== 'shadow-file'),
  ];

  for (const record of needsShadowFile) {
    // Locate the absolute dirPath for this record (stored as relative in registry)
    for (const [dirPath, name] of resolvedDirs) {
      const relPath = path.relative(process.cwd(), dirPath).replace(/\\/g, '/');
      if (relPath === record.path || dirPath === record.path) {
        // ensureShadowFile is idempotent: skips if file already valid.
        ensureShadowFile(dirPath, name, record.id, modulesRoots);
        break;
      }
    }
  }
}
