// Auto-generated by kerith sync-preload v2.0.0-alpha.1. Do not edit.
// To regenerate: npx kerith sync-preload

import { registerHooks } from 'node:module';
import { pathToFileURL, fileURLToPath } from 'node:url';
import { resolve, dirname } from 'node:path';
import { createResolveHook } from 'file:///C:/Users/Keiver/Desktop/Projects/Projects-Ideas/CLI/KerithJS/Kerith/packages/core/dist/preload/preload-hook.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

const KERITH_PRELOAD_CONFIG = {
  modulesDir: resolve(__dirname, '../src/modules'),
  aliases: {
    '@modules': resolve(__dirname, '../src/modules')
  },
  preloaded: true,
  _version: '2.0.0-alpha.1'
};

globalThis.__KERITH_PRELOAD_CONFIG__ = KERITH_PRELOAD_CONFIG;

const resolveHook = createResolveHook(KERITH_PRELOAD_CONFIG.aliases);

registerHooks({
  resolve: resolveHook
});

