// Auto-generated by kerith sync-preload v2.0.0-alpha.1. Do not edit.
// To regenerate: npx kerith sync-preload

import { registerHooks } from 'node:module';
import { pathToFileURL, fileURLToPath } from 'node:url';
import { resolve, dirname } from 'node:path';
import { createResolveHook } from '@kerith/core/preload-hook';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Preload configuration
const KERITH_PRELOAD_CONFIG = {
  modulesDir: resolve(__dirname, '../src'),
  aliases: {
    '@modules': resolve(__dirname, '../src'),
    '@modules/health': resolve(__dirname, '../src/modules/health'),
    '@modules/consumer': resolve(__dirname, '../src/modules/consumer'),
  },
  preloaded: true,
  _version: '2.0.0-alpha.1'
};

globalThis.__KERITH_PRELOAD_CONFIG__ = KERITH_PRELOAD_CONFIG;

// Create resolve hook with precomputed alias structures at top-level
const resolveHook = createResolveHook(KERITH_PRELOAD_CONFIG.aliases);

// Register the hook directly with registerHooks()
registerHooks({
  resolve: resolveHook
});
