// Auto-generated by nodulus sync-preload v1.5.0. Do not edit.
// To regenerate: npx nodulus sync-preload

import { register } from 'node:module';
import { pathToFileURL, fileURLToPath } from 'node:url';
import { resolve, dirname } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));

const NODULUS_PRELOAD_CONFIG = {
  modulesDir: resolve(__dirname, '../src/modules'),
  aliases: {
    '@modules': resolve(__dirname, '../src/modules'),
  },
  preloaded: true,
  _version: '1.5.0'
};

globalThis.__NODULUS_PRELOAD_CONFIG__ = NODULUS_PRELOAD_CONFIG;

register(
  'file:///C:/Users/Keiver/Desktop/Projects/Projects-Ideas/CLI/Nodulus-App/Nodulus-Core/packages/core/dist/preload/preload-hook.js',
  { parentURL: pathToFileURL(resolve(__dirname, '../')).href, data: NODULUS_PRELOAD_CONFIG }
);
