// Auto-generated by Kerith sync-preload v1.8.2. Do not edit.
// To regenerate: npx kerith sync-preload

import { register } from 'node:module';
import { pathToFileURL, fileURLToPath } from 'node:url';
import { resolve, dirname } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));

const KERITH_PRELOAD_CONFIG = {
  modulesDir: resolve(__dirname, '../src/modules'),
  aliases: {
    '@modules': resolve(__dirname, '../src/modules'),
  },
  preloaded: true,
  _version: '1.8.2'
};

globalThis.__KERITH_PRELOAD_CONFIG__ = KERITH_PRELOAD_CONFIG;

register(
  new URL('./dist/preload/preload-hook.js', import.meta.url),
  { parentURL: pathToFileURL(resolve(__dirname, '../')).href, data: KERITH_PRELOAD_CONFIG }
);
