import { describe, it, expect } from 'vitest';
import { generatePreloadFile } from '../../src/cli/lib/preload-generator.js';
import { execSync } from 'node:child_process';
import path from 'node:path';
import fs from 'node:fs';
import os from 'node:os';

describe('Preload Generator (preload-generator.ts)', () => {
  const mockConfig = {
    modules: 'src/modules/*',
    aliases: {
      '@shared': 'src/shared',
      '@db': 'src/database'
    },
    prefix: '',
    strict: true,
    resolveAliases: true,
    logger: () => {},
    logLevel: 'info' as any,
    nits: { enabled: true },
    requirePreloader: false
  };

  const fakeCwd = process.cwd();
  const version = '1.5.0-test';

  it('generatePreloadFile() produces a string that passes node --check', () => {
    const output = generatePreloadFile(mockConfig, version, fakeCwd);
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'nodulus-test-'));
    // Use .mjs to enforce ESM syntax parsing in node --check
    const tmpFile = path.join(tmpDir, 'preload.mjs'); 
    
    fs.writeFileSync(tmpFile, output, 'utf8');
    
    expect(() => {
      execSync(`node --check "${tmpFile}"`, { stdio: 'pipe' });
    }).not.toThrow();

    // cleanup
    fs.unlinkSync(tmpFile);
    fs.rmdirSync(tmpDir);
  });

  it('generated file contains absolute resolved paths for user aliases', () => {
    const output = generatePreloadFile(mockConfig, version, fakeCwd);
    
    // Check if @shared resolves to ../src/shared (since it's relative to .nodulus)
    expect(output).toContain("'@shared': resolve(__dirname, '../src/shared')");
    expect(output).toContain("'@db': resolve(__dirname, '../src/database')");
  });

  it('generated file contains _version matching the package version', () => {
    const output = generatePreloadFile(mockConfig, version, fakeCwd);
    expect(output).toContain(`_version: '${version}'`);
  });

  it('generated file contains "do not edit" comment', () => {
    const output = generatePreloadFile(mockConfig, version, fakeCwd);
    expect(output).toContain(`// Auto-generated by nodulus sync-preload v${version}. Do not edit.`);
    expect(output).toContain('// To regenerate: npx nodulus sync-preload');
  });

  it('same config produces the exact same output (idempotency)', () => {
    const output1 = generatePreloadFile(mockConfig, version, fakeCwd);
    const output2 = generatePreloadFile(mockConfig, version, fakeCwd);
    
    expect(output1).toEqual(output2);
  });

  it('paths correctly use ../ relative to .nodulus/ directory', () => {
    const output = generatePreloadFile(mockConfig, version, fakeCwd);
    
    // modulesDir should point to ../src/modules
    expect(output).toContain("modulesDir: resolve(__dirname, '../src/modules')");
  });
  it('changing modules glob path produces different output with the new path', () => {
    const originalOutput = generatePreloadFile(mockConfig, version, fakeCwd);
    
    const newConfig = {
      ...mockConfig,
      modules: 'src/api/*'
    };
    
    const newOutput = generatePreloadFile(newConfig, version, fakeCwd);
    
    expect(originalOutput).not.toEqual(newOutput);
    expect(newOutput).toContain("modulesDir: resolve(__dirname, '../src/api')");
  });

  it('changing nodulus-core version produces different output', () => {
    const originalOutput = generatePreloadFile(mockConfig, version, fakeCwd);
    const newOutput = generatePreloadFile(mockConfig, '2.0.0-test', fakeCwd);
    
    expect(originalOutput).not.toEqual(newOutput);
    expect(newOutput).toContain("_version: '2.0.0-test'");
  });
});
