import { describe, it, expect, beforeAll } from 'vitest';
import { generatePreloadFile } from '../../src/cli/lib/preload-generator.js';
import { execSync } from 'node:child_process';
import path from 'node:path';
import fs from 'node:fs';
import os from 'node:os';
import { vi } from 'vitest';

vi.mock('../../src/bootstrap/scanner.js', () => ({
  // Include all fields of ScanResult so the generator loop over scanResult.modules
  // doesn't throw "is not iterable". Tests that need modules populated use
  // vi.mocked(scanFromConfig).mockResolvedValueOnce(...) or rely on the default.
  scanFromConfig: vi.fn().mockResolvedValue({ domains: [], modules: [], submodules: [], shared: [] })
}));

describe('Preload Generator (preload-generator.ts)', () => {
  const mockConfig = {
    modules: 'src/modules/*',
    aliases: {
      '@shared': 'src/shared',
      '@db': 'src/database'
    },
    prefix: '',
    strict: true,
    resolveAliases: true,
    logger: () => {},
    logLevel: 'info' as any,
    nits: { enabled: true },
    requirePreloader: false
  };

  const fakeCwd = process.cwd();
  const version = '1.5.0-test';

  it('generatePreloadFile() produces a string that passes node --check', async () => {
    const output = await generatePreloadFile(mockConfig, version, fakeCwd);
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'kerith-test-'));
    // Use .mjs to enforce ESM syntax parsing in node --check
    const tmpFile = path.join(tmpDir, 'preload.mjs'); 
    
    fs.writeFileSync(tmpFile, output, 'utf8');
    
    expect(() => {
      execSync(`node --check "${tmpFile}"`, { stdio: 'pipe' });
    }).not.toThrow();

    // cleanup
    fs.unlinkSync(tmpFile);
    fs.rmdirSync(tmpDir);
  });

  it('generated file contains absolute resolved paths for user aliases', async () => {
    const output = await generatePreloadFile(mockConfig, version, fakeCwd);
    
    // Check if @shared resolves to ../src/shared (since it's relative to .kerith)
    expect(output).toContain("'@shared': resolve(__dirname, '../src/shared')");
    expect(output).toContain("'@db': resolve(__dirname, '../src/database')");
  });

  it('generated file contains _version matching the package version', async () => {
    const output = await generatePreloadFile(mockConfig, version, fakeCwd);
    expect(output).toContain(`_version: '${version}'`);
  });

  it('generated file contains "do not edit" comment', async () => {
    const output = await generatePreloadFile(mockConfig, version, fakeCwd);
    expect(output).toContain(`// Auto-generated by kerith sync-preload v${version}. Do not edit.`);
    expect(output).toContain('// To regenerate: npx kerith sync-preload');
  });

  it('same config produces the exact same output (idempotency)', async () => {
    const output1 = await generatePreloadFile(mockConfig, version, fakeCwd);
    const output2 = await generatePreloadFile(mockConfig, version, fakeCwd);
    
    expect(output1).toEqual(output2);
  });

  it('paths correctly use ../ relative to .kerith/ directory', async () => {
    const output = await generatePreloadFile(mockConfig, version, fakeCwd);
    
    // modulesDir should point to ../src/modules
    expect(output).toContain("modulesDir: resolve(__dirname, '../src/modules')");
  });

  it('changing modules glob path produces different output with the new path', async () => {
    const originalOutput = await generatePreloadFile(mockConfig, version, fakeCwd);
    
    const newConfig = {
      ...mockConfig,
      modules: 'src/api/*'
    };
    
    const newOutput = await generatePreloadFile(newConfig, version, fakeCwd);
    
    expect(originalOutput).not.toEqual(newOutput);
    expect(newOutput).toContain("modulesDir: resolve(__dirname, '../src/api')");
  });

  it('changing kerith-core version produces different output', async () => {
    const originalOutput = await generatePreloadFile(mockConfig, version, fakeCwd);
    const newOutput = await generatePreloadFile(mockConfig, '2.0.0-test', fakeCwd);
    
    expect(originalOutput).not.toEqual(newOutput);
    expect(newOutput).toContain("_version: '2.0.0-test'");
  });

  // ── Regression: Fix 1 — @modules/<name> must resolve to the module's real dirPath ──
  //
  // Before the fix, sync-preload only emitted a single '@modules' wildcard pointing
  // to the origin directory.  `@modules/beta` was therefore resolved as `origin/beta`
  // even when beta lives at `src/modules/beta`.  The fix adds one exact alias per
  // module using the scanner-provided dirPath.
  //
  // This test pins the exact shape of the generated preload.js for the nested-module
  // case so the bug cannot regress without breaking CI.

  describe('Fix 1 regression — exact per-module aliases in generated preload', () => {
    // scanFromConfig is mocked at the top of this file via vi.mock().
    // We reference the mock handle here so we can override its return value per-test.
    let scanMock: ReturnType<typeof vi.fn>;

    beforeAll(async () => {
      const scanner = await import('../../src/bootstrap/scanner.js') as any;
      scanMock = vi.mocked(scanner.scanFromConfig);
    });

    it('emits exact @modules/<name> aliases for flat modules (src/<name>)', async () => {
      scanMock.mockResolvedValueOnce({
        domains: [],
        submodules: [],
        shared: [],
        modules: [
          { name: 'alpha', dirPath: path.join(fakeCwd, 'src', 'alpha'), indexPath: path.join(fakeCwd, 'src', 'alpha', 'index.ts') },
          { name: 'beta',  dirPath: path.join(fakeCwd, 'src', 'beta'),  indexPath: path.join(fakeCwd, 'src', 'beta',  'index.ts') },
        ],
      });

      const config = { ...mockConfig, origin: 'src' };
      const output = await generatePreloadFile(config, version, fakeCwd);

      // Generic fallback must still exist
      expect(output).toContain("'@modules':");

      // Exact per-module entries must now be present — these are what the
      // preload hook's exactAliasMap picks up (highest priority).
      expect(output).toContain("'@modules/alpha': resolve(__dirname, '../src/alpha')");
      expect(output).toContain("'@modules/beta': resolve(__dirname, '../src/beta')");
    });

    it('emits exact @modules/<name> aliases for modules nested under src/modules/', async () => {
      scanMock.mockResolvedValueOnce({
        domains: [],
        submodules: [],
        shared: [],
        modules: [
          { name: 'alpha', dirPath: path.join(fakeCwd, 'src', 'modules', 'alpha'), indexPath: path.join(fakeCwd, 'src', 'modules', 'alpha', 'index.ts') },
          { name: 'beta',  dirPath: path.join(fakeCwd, 'src', 'modules', 'beta'),  indexPath: path.join(fakeCwd, 'src', 'modules', 'beta',  'index.ts') },
        ],
      });

      const config = { ...mockConfig, origin: 'src' };
      const output = await generatePreloadFile(config, version, fakeCwd);

      // Exact per-module entries must point to src/modules/<name>, NOT src/<name>
      expect(output).toContain("'@modules/alpha': resolve(__dirname, '../src/modules/alpha')");
      expect(output).toContain("'@modules/beta': resolve(__dirname, '../src/modules/beta')");

      // Sanity: a wrong resolution (e.g. '../src/alpha') must NOT appear for @modules/alpha
      expect(output).not.toContain("'@modules/alpha': resolve(__dirname, '../src/alpha')");
    });

    it('emits exact @modules/<name> aliases for modules inside a domain (src/<domain>/<name>)', async () => {
      scanMock.mockResolvedValueOnce({
        domains: [
          { name: 'billing', dirPath: path.join(fakeCwd, 'src', 'billing'), indexPath: path.join(fakeCwd, 'src', 'billing', 'index.ts'), options: {} },
        ],
        submodules: [],
        shared: [],
        modules: [
          {
            name: 'payments',
            dirPath: path.join(fakeCwd, 'src', 'billing', 'payments'),
            indexPath: path.join(fakeCwd, 'src', 'billing', 'payments', 'index.ts'),
            domain: 'billing',
          },
        ],
      });

      const config = { ...mockConfig, origin: 'src' };
      const output = await generatePreloadFile(config, version, fakeCwd);

      // Must resolve to the real domain-nested path
      expect(output).toContain("'@modules/payments': resolve(__dirname, '../src/billing/payments')");

      // Must NOT resolve to the origin root (the old buggy behaviour)
      expect(output).not.toContain("'@modules/payments': resolve(__dirname, '../src/payments')");
    });

    it('generic @modules fallback still present when modules list is empty', async () => {
      scanMock.mockResolvedValueOnce({
        domains: [],
        submodules: [],
        shared: [],
        modules: [],
      });

      const config = { ...mockConfig, origin: 'src' };
      const output = await generatePreloadFile(config, version, fakeCwd);

      // The generic '@modules' wildcard fallback must always be emitted
      expect(output).toContain("'@modules':");
    });
  });
});
