// Auto-generated by nodulus sync-preload v1.4.0. Do not edit.
// To regenerate: npx nodulus sync-preload

import { register } from 'node:module';
import { pathToFileURL, fileURLToPath } from 'node:url';
import { resolve, dirname } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));

const NODULUS_PRELOAD_CONFIG = {
  modulesDir: resolve(__dirname, '../src/modules'),
  aliases: {
    '@modules': resolve(__dirname, '../src/modules'),
  },
  preloaded: true,
  _version: '1.4.0'
};

globalThis.__NODULUS_PRELOAD_CONFIG__ = NODULUS_PRELOAD_CONFIG;

register(
  new URL('../node_modules/@vlynk-studios/nodulus-core/dist/preload-hook.js', import.meta.url),
  { parentURL: pathToFileURL(resolve(__dirname, '../')).href, data: NODULUS_PRELOAD_CONFIG }
);
