import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import type { KerithConfig } from '../../config/kerith-config.types.js';

// Resolved at CLI execution time — points to the bundled preload-hook alongside this file.
const HOOK_URL = pathToFileURL(
  path.resolve(fileURLToPath(import.meta.url), '../../preload/preload-hook.js')
).href;


import { scanFromConfig } from '../../bootstrap/scanner.js';

export async function generatePreloadFile(config: KerithConfig, version: string, cwd: string): Promise<string> {
  let modulesBase = '';
  if (config.origin) {
    modulesBase = config.origin.replace(/\\/g, '/');
  } else if (config.modules) {
    modulesBase = config.modules.replace(/\\/g, '/');
  }
  
  if (modulesBase.endsWith('/*')) {
      modulesBase = modulesBase.slice(0, -2);
    }

  const kerithDir = path.join(cwd, '.kerith');

  function getRelativePathStr(targetRelToCwd: string) {
    const targetAbs = path.resolve(cwd, targetRelToCwd);
    const rel = path.relative(kerithDir, targetAbs).replace(/\\/g, '/');
    // Ensure it starts with '.' or '..' 
    if (!rel.startsWith('.')) {
        return './' + rel;
    }
    return rel;
  }

  const escapeStr = (str: string) => str.replace(/'/g, "\\'");
  
  const modulesDirRel = escapeStr(getRelativePathStr(modulesBase));

  const aliases: Record<string, string> = {
    '@modules': `resolve(__dirname, '${modulesDirRel}')`
  };

  if (config.aliases) {
    for (const [alias, target] of Object.entries(config.aliases)) {
      aliases[escapeStr(alias)] = `resolve(__dirname, '${escapeStr(getRelativePathStr(target))}')`;
    }
  }

  // 2. Detect domains from origin
  const scanResult = await scanFromConfig(config, cwd);
  for (const domain of scanResult.domains) {
    const alias = escapeStr(`@${domain.name}`);
    aliases[alias] = `resolve(__dirname, '${escapeStr(getRelativePathStr(domain.dirPath))}')`;
  }

  // 3. Add shared aliases from scanResult
  for (const sharedEntry of (scanResult.shared ?? [])) {
    const alias = escapeStr(sharedEntry.alias);
    aliases[alias] = `resolve(__dirname, '${escapeStr(getRelativePathStr(sharedEntry.path))}')`;
  }


  const aliasesEntries = Object.entries(aliases)
    .map(([key, val]) => `    '${key}': ${val},`)
    .join('\n');

  return `// Auto-generated by kerith sync-preload v${version}. Do not edit.
// To regenerate: npx kerith sync-preload

import { register } from 'node:module';
import { pathToFileURL, fileURLToPath } from 'node:url';
import { resolve, dirname } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));

const KERITH_PRELOAD_CONFIG = {
  modulesDir: resolve(__dirname, '${modulesDirRel}'),
  aliases: {
${aliasesEntries}
  },
  preloaded: true,
  _version: '${escapeStr(version)}'
};

globalThis.__KERITH_PRELOAD_CONFIG__ = KERITH_PRELOAD_CONFIG;

register(
  '${HOOK_URL}',
  { parentURL: pathToFileURL(resolve(__dirname, '../')).href, data: KERITH_PRELOAD_CONFIG }
);
`;
}
