import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import type { NodulusConfig } from '../../config/nodulus-config.types.js';

// Resolved at CLI execution time — points to the bundled preload-hook alongside this file.
const HOOK_URL = pathToFileURL(
  path.resolve(fileURLToPath(import.meta.url), '../../preload/preload-hook.js')
).href;


export function generatePreloadFile(config: NodulusConfig, version: string, cwd: string): string {
  let modulesBase = 'src/modules';
  if (config.modules) {
    modulesBase = config.modules.replace(/\\/g, '/');
    if (modulesBase.endsWith('/*')) {
      modulesBase = modulesBase.slice(0, -2);
    }
  }

  const nodulusDir = path.join(cwd, '.nodulus');

  function getRelativePathStr(targetRelToCwd: string) {
    const targetAbs = path.resolve(cwd, targetRelToCwd);
    const rel = path.relative(nodulusDir, targetAbs).replace(/\\/g, '/');
    // Ensure it starts with '.' or '..' 
    if (!rel.startsWith('.')) {
        return './' + rel;
    }
    return rel;
  }

  const escapeStr = (str: string) => str.replace(/'/g, "\\'");
  
  const modulesDirRel = escapeStr(getRelativePathStr(modulesBase));

  const aliases: Record<string, string> = {
    '@modules': `resolve(__dirname, '${modulesDirRel}')`
  };

  if (config.aliases) {
    for (const [alias, target] of Object.entries(config.aliases)) {
      aliases[escapeStr(alias)] = `resolve(__dirname, '${escapeStr(getRelativePathStr(target))}')`;
    }
  }

  const aliasesEntries = Object.entries(aliases)
    .map(([key, val]) => `    '${key}': ${val},`)
    .join('\n');

  return `// Auto-generated by nodulus sync-preload v${version}. Do not edit.
// To regenerate: npx nodulus sync-preload

import { register } from 'node:module';
import { pathToFileURL, fileURLToPath } from 'node:url';
import { resolve, dirname } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));

const NODULUS_PRELOAD_CONFIG = {
  modulesDir: resolve(__dirname, '${modulesDirRel}'),
  aliases: {
${aliasesEntries}
  },
  preloaded: true,
  _version: '${escapeStr(version)}'
};

globalThis.__NODULUS_PRELOAD_CONFIG__ = NODULUS_PRELOAD_CONFIG;

register(
  '${HOOK_URL}',
  { parentURL: pathToFileURL(resolve(__dirname, '../')).href, data: NODULUS_PRELOAD_CONFIG }
);
`;
}
