import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import type { KerithConfig } from '../../config/kerith-config.types.js';

// Default package specifier — used as fallback when the file path cannot be resolved.
const HOOK_URL = '@kerith/core/preload-hook';


import { scanFromConfig } from '../../bootstrap/scanner.js';

export async function generatePreloadFile(config: KerithConfig, version: string, cwd: string): Promise<string> {
  let modulesBase = '';
  if (config.origin) {
    modulesBase = config.origin.replace(/\\/g, '/');
  } else if (config.modules) {
    modulesBase = config.modules.replace(/\\/g, '/');
  }
  
  if (modulesBase.endsWith('/*')) {
      modulesBase = modulesBase.slice(0, -2);
    }

  const kerithDir = path.join(cwd, '.kerith');

  function getRelativePathStr(targetRelToCwd: string) {
    const targetAbs = path.resolve(cwd, targetRelToCwd);
    const rel = path.relative(kerithDir, targetAbs).replace(/\\/g, '/');
    // Ensure it starts with '.' or '..' 
    if (!rel.startsWith('.')) {
        return './' + rel;
    }
    return rel;
  }

  const escapeStr = (str: string) => str.replace(/'/g, "\\'");
  
  const modulesDirRel = escapeStr(getRelativePathStr(modulesBase));

  const aliases: Record<string, string> = {
    '@modules': `resolve(__dirname, '${modulesDirRel}')`
  };

  if (config.aliases) {
    for (const [alias, target] of Object.entries(config.aliases)) {
      aliases[escapeStr(alias)] = `resolve(__dirname, '${escapeStr(getRelativePathStr(target))}')`;
    }
  }

  // 2. Detect domains from origin
  const scanResult = await scanFromConfig(config, cwd);
  for (const domain of scanResult.domains) {
    const alias = escapeStr(`@${domain.name}`);
    aliases[alias] = `resolve(__dirname, '${escapeStr(getRelativePathStr(domain.dirPath))}')`;
  }

  // 3. Add shared aliases from scanResult
  for (const sharedEntry of (scanResult.shared ?? [])) {
    const alias = escapeStr(sharedEntry.alias);
    aliases[alias] = `resolve(__dirname, '${escapeStr(getRelativePathStr(sharedEntry.path))}')`;
  }


  const aliasesEntries = Object.entries(aliases)
    .map(([key, val]) => `    '${key}': ${val},`)
    .join('\n');

  // Resolve the real absolute path of the preload-hook file at generation time.
  // This avoids a Node.js v24 bug on Windows where the ESM loader worker thread
  // does not follow directory junctions (created by `npm install file:...`) when
  // resolving package specifiers, causing ERR_MODULE_NOT_FOUND at runtime.
  let hookUrl: string;
  try {
    const { createRequire } = await import('node:module');
    const cwdPkgPath = path.join(cwd, 'node_modules', '@kerith', 'core', 'package.json');
    const req = createRequire(cwdPkgPath);
    const resolvedHookPath = req.resolve('./dist/preload/preload-hook.js');
    hookUrl = pathToFileURL(resolvedHookPath).href;
  } catch {
    // Fallback to package specifier if resolution fails (e.g., not installed via file:)
    hookUrl = HOOK_URL;
  }

  return `// Auto-generated by kerith sync-preload v${version}. Do not edit.
// To regenerate: npx kerith sync-preload

import { register } from 'node:module';
import { pathToFileURL, fileURLToPath } from 'node:url';
import { resolve, dirname } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));

const KERITH_PRELOAD_CONFIG = {
  modulesDir: resolve(__dirname, '${modulesDirRel}'),
  aliases: {
${aliasesEntries}
  },
  preloaded: true,
  _version: '${escapeStr(version)}'
};

globalThis.__KERITH_PRELOAD_CONFIG__ = KERITH_PRELOAD_CONFIG;

register(
  '${hookUrl}',
  { parentURL: pathToFileURL(resolve(__dirname, '../')).href, data: KERITH_PRELOAD_CONFIG }
);
`;
}
