/**
 * scaffold.ts — Programmatic generation via subprocess for E2E tests.
 */

import { spawn } from 'node:child_process';
import path from 'node:path';
import fs from 'node:fs';
import os from 'node:os';
import { fileURLToPath } from 'node:url';
import type { ScaffoldOptions } from './types.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const MONOREPO_ROOT = path.resolve(__dirname, '../../../');
const CREATE_KERITH_BIN = path.resolve(MONOREPO_ROOT, 'packages/create-kerith/dist/index.js');

/**
 * Spawns a child process and waits for exit code 0.
 * If it fails, captures and throws full stdout/stderr for debugging.
 */
function spawnAsync(command: string, args: string[], cwd: string): Promise<void> {
  return new Promise((resolve, reject) => {
    // shell is required on Windows for npm/npx
    const isWin = process.platform === 'win32';
    const child = spawn(command, args, { cwd, shell: isWin });

    let stdout = '';
    let stderr = '';

    if (child.stdout) {
      child.stdout.on('data', (data) => { stdout += data.toString(); });
    }
    if (child.stderr) {
      child.stderr.on('data', (data) => { stderr += data.toString(); });
    }

    child.on('error', (err) => reject(new Error(`[spawn] Failed to start "${command}": ${err.message}`)));

    child.on('close', (code) => {
      if (code === 0) {
        resolve();
      } else {
        const errorMsg = `Command "${command} ${args.join(' ')}" failed with exit code ${code}.\n\nSTDOUT:\n${stdout}\n\nSTDERR:\n${stderr}`;
        reject(new Error(errorMsg));
      }
    });
  });
}

/**
 * Generates a Kerith project programmatically using create-kerith in a temp directory,
 * overwrites its package.json dependencies to point to the local tarballs,
 * and completely initializes it (npm install + sync) so it's ready to boot.
 * 
 * @returns The absolute path to the generated temporary directory.
 */
export async function runCreateKerith(options: ScaffoldOptions): Promise<string> {
  const {
    name,
    template,
    language,
    channels = [],
    redis,
    socketio,
    port,
    routePrefix,
    tarballs,
  } = options;

  const runId = Math.floor(Date.now() + Math.random() * 1000).toString(36);
  const dir = path.join(os.tmpdir(), `kerith-e2e-${name.replace(/[^a-z0-9]/gi, '-')}-${runId}`);

  const createArgs = [
    CREATE_KERITH_BIN,
    '--yes',
    '--no-install',
    '--out-dir', dir,
    '--template', template,
    '--language', language
  ];

  if (channels.length > 0) createArgs.push('--channels', channels.join(','));
  if (redis) createArgs.push('--redis');
  if (socketio) createArgs.push('--socketio');
  if (port) createArgs.push('--port', String(port));
  if (routePrefix) createArgs.push('--prefix', routePrefix);

  // Spawnea create-kerith
  await spawnAsync('node', createArgs, process.cwd());

  // Post-generación, antes de instalar: reescribir package.json
  const pkgPath = path.join(dir, 'package.json');
  if (!fs.existsSync(pkgPath)) {
    throw new Error(`[runCreateKerith] Expected package.json at ${pkgPath}, but it was not found.`);
  }

  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));

  for (const depType of ['dependencies', 'devDependencies']) {
    if (pkg[depType]) {
      for (const [depName, tarballPath] of Object.entries(tarballs)) {
        if (pkg[depType][depName]) {
          pkg[depType][depName] = `file:${tarballPath}`;
        }
      }
    }
  }
  fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2));

  // Ejecutar npm install (aislado, via spawn)
  await spawnAsync('npm', ['install', '--silent'], dir);

  // Ejecutar npx kerith sync-preload explícitamente desde el harness
  await spawnAsync('npx', ['kerith', 'sync-preload'], dir);

  if (language === 'ts') {
    await spawnAsync('npx', ['kerith', 'sync-tsconfig'], dir);
  }

  // Validaciones antes de devolver el dir (evitar timeouteos confusos en el test)
  const preloadPath = path.join(dir, '.kerith/preload.js');

  if (!fs.existsSync(preloadPath)) {
    throw new Error(`[runCreateKerith] Validation failed: ${preloadPath} was not generated by sync-preload.`);
  }

  return dir;
}
